version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/bloged
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 1800
      runas: root
