version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: BlogedWebapp/Dockerfile
    container_name: BlogedWebapp
    ports:
     - 8888:80
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
  unit_tests:
    build:
      context: .
      dockerfile: tests/UnitTests/Dockerfile
    container_name: UnitTests
    depends_on:
     - web

   