version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: BlogedWebapp/Dockerfile
    container_name: BlogedWebapp
    ports:
     - 7000:80
     - 7001:443
    environment:
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
    entrypoint: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
   