version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: BlogedWebapp/Dockerfile
    container_name: BlogedWebapp
    ports:
     - 8080:80
    volumes:
     - wwwroot-folder:/app/wwwroot
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
     - BLOGED_DB_CONN=${BLOGED_DB_CONN}
    
  api_unit_tests:
    build:
      context: .
      dockerfile: tests/UnitTests/Dockerfile
    container_name: ApiUnitTests

volumes:
  wwwroot-folder:


   