version: '3.8'

services:
  frontend:
    image: samuele4589/bloged_frontend:latest
    container_name: BlogedFrontend
    volumes:
     - wwwroot-folder:/app/wwwroot
    entrypoint: /bin/sh /app/deploy.sh

volumes:
  wwwroot-folder:
