#!/bin/bash

cd /home/ubuntu/bloged
docker-compose --file docker-compose.frontend.yml pull
docker-compose --file docker-compose.api.yml pull
docker-compose -f docker-compose.api.yml -f docker-compose.frontend.yml build --pull
docker-compose -f docker-compose.api.yml -f docker-compose.frontend.yml up -d