#!/bin/bash

#stopping containers in execution
echo "Stopping BlogedWebApp Container"
docker stop BlogedWebapp

echo "Running Containers:"
docker ps

#removing containers
echo "Removing containers"
docker rm --force BlogedWebapp
docker rm --force BlogedFrontend

echo "Removing images"
docker image prune --force
docker images --all

rm -r /home/ubuntu/bloged
mkdir /home/ubuntu/bloged