#!/bin/bash

sleep 1

#stopping containers in execution
echo "Stopping BlogedWebApp Container"
docker stop BlogedWebapp

echo "Running Containers:"
docker ps

#removing containers
echo "Removing containers"
docker rm --force BlogedWebapp
docker rm --force BlogedFrontend

echo "Removing images"
docker image prune --all --force
docker images --all

sleep 1

rm -r /home/ubuntu/bloged
mkdir /home/ubuntu/bloged