name: Api Continuous Integration

on:
  push:
    branches: [ api ]
  pull_request:
    branches: [ api ]
    
env:
  REPO: https://Samuele458:${{secrets.GITHUB_TOKEN}}@github.com/Samuele458/bloged.git
  MASTER_REPO: https://github.com/samuele458/bloged.git
  MASTER_BRANCH: preproduction
 
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building stack
      run: docker-compose -f docker-compose.api.yml build
    - name: Running unit-tests
      run: docker-compose -f docker-compose.api.yml up api_unit_tests
    - name: Checking unit tests
      run: exit $(docker container inspect ApiUnitTests --format '{{.State.ExitCode}}')
    - name: Merging to preproduction branch
      run: |
            git clone ${{env.REPO}} -b ${GITHUB_REF##*/} tmp
            cd tmp
            git config user.name "Samuele458"
            git config user.email "samuele.girgenti458@gmail.com"
            git config pull.rebase false
            git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
            git checkout ${{env.MASTER_BRANCH}}
            git merge ${GITHUB_REF##*/}
            git push --all origin
            

