name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  #build:
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Build the stack
    #  run: docker-compose -f docker-compose.yml build
    #- name: Running unit-tests
    #  run: docker-compose -f docker-compose.yml up unit_tests
    #- name: Checking unit tests
    #  run: exit $(docker container inspect UnitTests --format '{{.State.ExitCode}}')
      
  continuous-deployment:
    runs-on: ubuntu-latest
    #needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name bloged-app \
            --deployment-group-name BlogedDeploymentGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
