name: Frontend Continuous Integration

on:
  push:
    branches: [frontend]
  pull_request:
    branches: [frontend]

env:
  REPO: https://Samuele458:${{secrets.GITHUB_TOKEN}}@github.com/Samuele458/bloged.git
  MASTER_REPO: https://github.com/samuele458/bloged.git
  MASTER_BRANCH: preproduction

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building stack
        run: docker-compose -f docker-compose.frontend-local.yml build
      - name: Building frontend dist
        run: docker-compose -f docker-compose.frontend-local.yml up
      - name: Checking frontend container status
        run: exit $(docker container inspect BlogedFrontend --format '{{.State.ExitCode}}')
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Pushing images to Docker Hub
        run: |
          docker tag bloged_frontend:latest ${{secrets.DOCKER_USER}}/bloged_frontend
          docker push ${{secrets.DOCKER_USER}}/bloged_frontend:latest
      - name: Merging to preproduction branch
        run: |
          git clone ${{env.REPO}} -b ${GITHUB_REF##*/} tmp
          cd tmp
          git config user.name "Samuele458"
          git config user.email "samuele.girgenti458@gmail.com"
          git config pull.rebase false
          git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
          git checkout ${{env.MASTER_BRANCH}}
          git merge ${GITHUB_REF##*/}
          git push --all origin
